#!/bin/sh

# install nodejs
pkg install nodejs

# make mx executable
chmod +x "./music-cli/android-termux/mx"

# cp mx to $PATH so we can call it wherever
cp "./music-cli/android-termux/mx" /data/data/com.termux/files/usr/bin/mx